### PR TITLE
UPDATE cloudformation.vim - fix spelling error 'cloudformaiton'

### PR DESCRIPTION
**Pull request by JohnVonNeumann**
Was reading through the code and found a minor (and isolated spelling error), fixing for obvious reasons.

### CODE REVIEW

**Comment by JohnVonNeumann** [comment]
This is the PR, you should have an accept/merge button below if I'm understanding correctly?
Cheers!

**Comment by JohnVonNeumann** [comment]
Hey mate, this PR is still open, you can either accept it or close it if you're not happy with it!

**Comment by speshak** [comment]
I must have missed the notification when you opened this.  Sorry about the delay.

**Comment by JohnVonNeumann** [comment]
No issues man! Have a good one!

**Pull request merged**
